#!/usr/bin/perl

use strict;
use warnings;

my $dbname = $ENV{DBNAME} or die "Must specify DBNAME";

system("dropdb $dbname");
system("createdb $dbname");
system("psql $dbname -f db/theschwartz.sql");
